[package]
name = "gdrs_parse"
version = "0.1.0"
authors = ["Jameson Ernst <j.patrick.ernst@gmail.com>"]

[dependencies]
gdrs_obj = { path = "../gdrs_obj" }
clang = "0.13.0"
serde_json = "0.8.2"
docopt = "0.6.86"
