[package]
name = "gdrs_host"
version = "0.1.0"
authors = ["Jameson Ernst <j.patrick.ernst@gmail.com>"]
publish = false

[lib]
crate-type = ["staticlib"]

[dependencies]
gdrs_alloc = { path = "gdrs_alloc" }
gdrs = { path = "../gdrs" }
