[package]
name = "gdrs-host"
version = "0.1.0"
authors = ["Jameson Ernst <j.patrick.ernst@gmail.com>"]
publish = false

[lib]
crate-type = ["staticlib"]

[dependencies]
gdrs-alloc = { path = "gdrs-alloc" }
gdrs = { path = "../gdrs" }
