[package]
name = "gdrs"
version = "0.1.0"
authors = ["Jameson Ernst <j.patrick.ernst@gmail.com>"]
publish = false
build = "build.rs"

[lib]
crate-type = ["rlib", "dylib"]

[build-dependencies]
gdrs_gen = { path = "gdrs_gen" }

[dependencies]
gdrs_macros = { path = "gdrs_macros" }
